disabled_rules:
  - trailing_whitespace # seems like Xcode does this by default

opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
  - vertical_whitespace
#  - missing_docs # broken
  - closure_spacing
  - conditional_returns_on_newline
  - explicit_init
  - overridden_super_call
  - redundant_nil_coalesing
#  - switch_case_on_newline # broken
  
included:
  - Source
  - Tests
  
excluded:
  - Pods
  - Example

reporter: "xcode"

line_length: 150
